id: cursor-mcp-installer
name: Cursor MCP Installer
description: A tool to install MCP servers in Cursor

services:
  - id: mcp-installer-service
    name: MCP Installer Service
    protocol: mcp
    build:
      context: .
      dockerfile: Dockerfile
    transport:
      type: stdio

tools:
  - id: install_repo_mcp_server
    name: install_repo_mcp_server
    description: Install an MCP server via npx or uvx
    parameters:
      name:
        type: string
        description: The package name of the MCP server
      
  - id: install_local_mcp_server
    name: install_local_mcp_server
    description: Install an MCP server whose code is cloned locally on your computer
    parameters:
      path:
        type: string
        description: The path to the MCP server code cloned on your computer
  
  - id: add_to_cursor_config
    name: add_to_cursor_config
    description: Add any MCP server to Cursor's configuration
    parameters:
      name:
        type: string
        description: Display name for the MCP server in Cursor 