id: cursor-mcp-installer
name: Cursor MCP Installer
description: A tool to install MCP servers in Cursor

services:
  - id: mcp-installer-service
    name: MCP Installer Service
    protocol: mcp
    build:
      context: .
      dockerfile: Dockerfile
    transport:
      type: stdio

functions:
  - id: install_repo_mcp_server
    name: install_repo_mcp_server
    description: Install an MCP server via npx or uvx
    parameters:
      type: object
      properties:
        name:
          type: string
          description: The package name of the MCP server
      required:
        - name
      
  - id: install_local_mcp_server
    name: install_local_mcp_server
    description: Install an MCP server whose code is cloned locally on your computer
    parameters:
      type: object
      properties:
        path:
          type: string
          description: The path to the MCP server code cloned on your computer
      required:
        - path
  
  - id: add_to_cursor_config
    name: add_to_cursor_config
    description: Add any MCP server to Cursor's configuration
    parameters:
      type: object
      properties:
        name:
          type: string
          description: Display name for the MCP server in Cursor
      required:
        - name 